theme: jekyll-theme-cayman
title: Syed Khawar Ali
description: Feel free to bookmark this to keep an eye on my project updates
baseurl: ""
url: "http://iotech.pk/"
github_username: syedkhawarali
twitter_username: khawarali65
