theme: jekyll-theme-cayman
url: "http://username.github.io"
baseurl: ""
avatar: "https://avatars3.githubusercontent.com/u/15910422?v=3&u=4ddab3843b5b5c7bc87dfe7236a94bd64d2632a7&s=200"
title: Khawar Ali
description: Feel free to bookmark this to keep an eye on my project updates
