theme: jekyll-theme-cayman
url: "http://khawarali5.github.io"
baseurl: ""
avatar: "https://avatars3.githubusercontent.com/u/15910422?v=3&u=4ddab3843b5b5c7bc87dfe7236a94bd64d2632a7&s=200"
title: Khawar Ali
description: Feel free to bookmark this to keep an eye on my project updates
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"
