theme: jekyll-theme-architect
title: Syed Khawar Ali
description: "designer, developer, footballer"
baseurl: ""
url: "https://syedkhawarali.github.io/"
github_username: syedkhawarali
twitter_username: khawarali65
