theme: jekyll-theme-minimal
title: Khawar Ali Shah
description: Feel free to bookmark this to keep an eye on my project updates
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
